global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Globalization;
global using System.Text.RegularExpressions;
global using AnyOfTypes;
global using AoC.Extensions;
global using AoC.Types;
global using LanguageExt;
global using Microsoft.Extensions.Logging;
global using SuperLinq;
global using static LanguageExt.Prelude;
